sequenceDiagram
    participant A as "Signal Acquisition and Preprocessing"
    participant B as "CW Modulation"
    participant C as "Neural Network Augmentation"
    participant D as "FDM Processing"
    participant E as "Dynamic Spectrum Access"
    participant F as "Reconfiguration"
    participant G as "Transmission"
    participant H as "Real-ime Control"
    participant M as "Linux OS" in "Torizon IoT Platform"
    participant N as "Remote Software Updates" in "Torizon IoT Platform"
    participant O as "Device Management" in "Torizon IoT Platform"
    participant I as "Network Interface" in "External Interfaces"

    A->>B: Raw Signal
    B->>C: Modulated Signal
    C->>D: Optimized Modulation
    D->>E: FDM Signal
    E->>F: Best Channels
    F->>G: Updated Transmission Parameters
    G->>H: Transmit Signal
    H->>A: Monitoring
    B-.->B1: Uses Dual Cortex-A53
    C-.->C1: Uses NPU
    H-.->H1: Uses Cortex-M7
    G->>I: Wi-Fi/Bluetooth
